# Generated by Django 2.2.14 on 2020-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
                ('pub_date', models.DateField()),
                ('author', models.CharField(default='', max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('img', models.ImageField(default='', upload_to='book_img')),
            ],
        ),
    ]
